### ISSUE TITLE
Other middlewares not working

### ISSUE THREAD

**Issue by TsChiEtA** [snickler/RSSCore#3]
I added this middleware to an already existing mvc middleware. In order to have the mvc still work with this middleware I had to add some code to the RSSMiddleware class to move on with the next middleware if the request path did not match the pattern.

```c#
public async Task Invoke(HttpContext context, RSSService rssService)
{
    if (context.Request.Path.Equals(_urlPath))
    {
        context.Response.ContentType = "application/rss+xml";
        var rssFeed = await rssService.BuildRSSFeed(_rssOptions).ConfigureAwait(false);
        if (!string.IsNullOrEmpty(rssFeed))
        {
            await context.Response.WriteAsync(rssFeed).ConfigureAwait(false);
        }
    }
    else
        await _next(context);
}
```

Maybe this is something you want to add.

**Comment by snickler** [comment]
@TsChiEtA - Great catch. Fixing now and new NuGet package coming

**Comment by snickler** [comment]
Fixed with latest merge into master. NuGet package is updating as we speak.
