### ISSUE TITLE
Setting RSSItem Categories or Authors does not work. 

### ISSUE THREAD

**Issue by davidomid** [snickler/RSSCore#5]
There's an issue with the RSSItem class which prevents Categories or Authors from being modified. 

It's caused by this part of the code. 

```
public List<string> Categories => new List<string>();
public List<string> Authors => new List<string>();
```

Property getters should be used with initialisers, instead of expression bodies. The idea is that we set the values by default to empty lists but then allow a developer to add/remove strings as necessary. The current code does not allow this, as instead it always returns a new empty list whenever the property is accessed. 

I'll create a pull request ASAP.

**Comment by snickler** [comment]
Ah. Thanks for this. I'll be home in about  10-15 minutes and will merge your PR in then.
________________________________

**Comment by snickler** [comment]
Merged and updated NuGet package.
