### ISSUE TITLE
RSSCore requirements do not match RSS specification

### ISSUE THREAD

**Issue by davidomid** [snickler/RSSCore#7]
According to the RSS specification written [here](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt), and validators such as [this one](https://validator.w3.org/feed/#validate_by_input), the following should be possible: 

- An RSSItem should have **at least either** a Title or Content. It doesn't need to have both. 
- Everything else is optional, including Authors and Categories. 

The following is considered a valid RSS feed: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel><title>Sample RSS Feed</title>
<description>Some Sample RSS Feed You'll Like</description>
<link>http://someaddress.com/</link>
<language>en-GB</language>
<managingEditor>managingeditor@someaddress.com</managingEditor>
<webMaster>webmaster@someaddress.com</webMaster>
<copyright>2017</copyright>
<lastBuildDate>Sat, 30 Jun 2018 15:10:38 GMT</lastBuildDate>
<item>
  <title>Sample Title 1</title>
  <guid>http://www.sampleaddress.com/sample-content-1</guid>
  <link>http://www.sampleaddress.com/sample-content-1</link>
  <description>Sample Content 1</description>
  <author>someuser@sampleaddress.com</author>
  <category>.NET</category>
  <pubDate>Sat, 30 Jun 2018 15:10:38 GMT</pubDate>
</item>
<item>
  <guid>http://www.sampleaddress.com/sample-content-2</guid>
  <link>http://www.sampleaddress.com/sample-content-2</link>
  <description>Sample Content 2</description>
  <category>.NET</category>
  <pubDate>Sat, 30 Jun 2018 15:10:38 GMT</pubDate>
</item>
<item>
  <title>Sample Title 3</title>
  <guid>http://www.sampleaddress.com/sample-content-3</guid>
  <link>http://www.sampleaddress.com/sample-content-3</link>
  <author>someotheruser@sampleaddress.com</author>
  <pubDate>Sat, 30 Jun 2018 15:10:38 GMT</pubDate>
</item>
<item>
  <title>Sample Title 4</title>
  <guid>http://www.sampleaddress.com/sample-content-4</guid>
  <link>http://www.sampleaddress.com/sample-content-4</link>
  <pubDate>Sat, 30 Jun 2018 15:10:38 GMT</pubDate>
</item></channel>
</rss>
```

However, it isn't currently possible to generate this using RSSCore as the following rules are enforced: 
- Title and Content are both required. This is currently enforced at run-time (ArgumentNullExceptions are thrown) and there is no indication at compile-time that either might be required. This can be better enforced by a constructor for the RSSItem class. 
- Authors and Categories are initialised as empty lists and the lists have to be added to after initialising the RSSItem. This produces ugly code that looks like this:

```csharp
var synd1 = new RSSItem()
{
     Content = "Sample Content 1",
     PermaLink = new Uri("http://www.sampleaddress.com/sample-content-1"),
     LinkUri = new Uri("http://www.sampleaddress.com/sample-content-1"),
     LastUpdated = DateTime.Now,
     PublishDate = DateTime.Now,
     Title = "Sample Title 1",
};
synd1.Categories.Add(".NET");
synd1.Authors.Add("someuser@sampleaddress.com");
```

Instead of this:

```csharp
var synd1 = new RSSItem("Sample Title 1", "Sample Content 1")
{
     PermaLink = new Uri("http://www.sampleaddress.com/sample-content-1"),
     LinkUri = new Uri("http://www.sampleaddress.com/sample-content-1"),
     LastUpdated = DateTime.Now,
     PublishDate = DateTime.Now,
     Categories = new List<string> { ".NET" },
     Authors = new List<string> { "someuser@sampleaddress.com" }
};
```

I'll create a pull request immediately which would resolve these issues. This would be a breaking change however, so I'll increment the major version.

**Comment by davidomid** [comment]
@snickler This issue and its related pull request has been sitting here for almost a year. Please advise if this can be resolved. 

If the project is no longer actively maintained, I am happy to take over.

**Comment by snickler** [comment]
Hi @davidomid , my extreme apologizes for missing this. It looks great to me, so I'm approving the PR.

**Comment by davidomid** [comment]
Hey @snickler, 

Thanks very much :) please can we have a release of the latest version to NuGet?

**Comment by snickler** [comment]
Yup. I'm going to get that going when I get some time this afternoon ??

Regards,
Jeremy Sinclair

________________________________

**Comment by davidomid** [comment]
Brilliant, thanks very much :)

**Comment by snickler** [comment]
Package is pushed. It should take about 5-10 mins to populate

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
